# create tuple with different data type
tup = ('shail',23,45.65,'raj')
print('tuple with different data type:')
print(tup)
num=(12,23,45.6,67)
print('tuple with numbers and print one item.')
print(num)
print('1 st element in tuple:')
print(num[1])
print('to convert a tuple to a string.')
arr=('p','y','t','h','o','n')
str=''.join(arr)
print(str)
print(num)
print('length of above tuple:',len(num))
tup=(1,2,1,3,2,5)
print(tup)
print('counting 1 in above tupple:')
print(tup.count(1))
